"""
KP Report Generator - Generate complete Markdown reports for KP System
"""

from kp_system import KPSystem, BhavaChalitSystem
from datetime import datetime
import json

class KPReportGenerator:
    """Generate comprehensive KP astrology reports in Markdown format"""

    def __init__(self):
        self.kp_system = KPSystem()
        self.bhava_system = BhavaChalitSystem()

    def generate_markdown_report(self, year: int, month: int, day: int, hour: int, minute: int,
                                latitude: float, longitude: float, timezone: str,
                                name: str = "Sample Chart", place: str = "New Delhi, India") -> str:
        """
        Generate complete KP report in Markdown format
        """
        # Get KP data
        kp_data = self.kp_system.generate_kp_astrosage_format(year, month, day, hour, minute, latitude, longitude, timezone)

        # Get Bhava Chalit data
        import swisseph as swe
        jd = swe.julday(year, month, day, hour + minute/60.0)
        # Get ascendant longitude for Bhava Chalit
        house_cusps = self.kp_system.get_kp_house_cusps(jd, latitude, longitude)
        ascendant_longitude = house_cusps.get(1, 0)

        # Create dummy planet positions for Bhava Chalit
        planet_data = self.kp_system.get_planet_positions_kp(jd)
        from models import PlanetPosition
        planets = {}
        for name, data in planet_data.items():
            planet = PlanetPosition()
            planet._abs_lon_sid = data['longitude']
            planets[name] = planet

        bhava_data = self.bhava_system.generate_bhava_chalit_chart(ascendant_longitude, planets)

        # Generate report
        report = f"""# Krishnamurti Paddhati (KP) Astrological Report

## Chart Information
- **Name**: {name}
- **Date of Birth**: {day:02d}/{month:02d}/{year}
- **Time of Birth**: {hour:02d}:{minute:02d}
- **Place**: {place}
- **Coordinates**: {latitude}°N, {longitude}°E
- **Timezone**: {timezone}
- **System**: Krishnamurti Paddhati (KP) with Swiss Ephemeris
- **House System**: Placidus
- **Ayanamsa**: KP Ayanamsa
- **Report Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

## Planetary Positions (KP Format)

{self._format_planets_table(kp_data.get('planets_table', []))}

---

## House Cusps (KP Format)

{self._format_cusps_table(kp_data.get('cusps_table', []))}

---

## Ruling Planets Analysis

{self._format_ruling_planets(kp_data.get('ruling_planets', {}))}

---

## KP Chart Layout

{self._format_kp_chart(kp_data.get('kp_chart', {}))}

---

## House Significators Analysis

{self._format_house_significators(kp_data.get('house_significators', {}))}

---

## Bhava Chalit Chart Comparison

{self._format_bhava_chart(bhava_data.get('bhava_chart', {}))}

---

## KP System Overview

### What is Krishnamurti Paddhati (KP)?

Krishnamurti Paddhati, developed by Prof. K.S. Krishnamurti, is a revolutionary approach to Vedic astrology that focuses on:

1. **Sub-Lord Theory**: Each planet has three levels of influence:
   - **Sign Lord**: Ruler of the zodiac sign
   - **Star Lord**: Ruler of the nakshatra (star constellation)
   - **Sub Lord**: Ruler of the sub-division within the nakshatra

2. **Placidus House System**: Unlike traditional equal houses, KP uses unequal house sizes based on geographical location

3. **Ruling Planets**: Special significance given to:
   - **Mo (Moon)**: Emotional and mental state
   - **Asc (Ascendant)**: Life path and personality
   - **Day Lord**: Planetary ruler of the day of birth

4. **Significator System**: Houses are analyzed through:
   - **Strong Significators**: Planets in the house, house cusp sub-lord
   - **Medium Significators**: Star lords of planets in the house
   - **Weak Significators**: Sub-lords of planets in the house

### Key Differences from Traditional Astrology

| Aspect | Traditional Vedic | KP System |
|--------|------------------|-----------|
| House System | Whole Sign (30° each) | Placidus (unequal sizes) |
| Focus | Sign positions | Sub-lord analysis |
| Predictions | General trends | Precise timing |
| Ayanamsa | Lahiri | KP Ayanamsa |
| Chart Reading | Multiple factors | Significator theory |

---

## Technical Details

### Calculation Methods
- **Planetary Positions**: Swiss Ephemeris calculations
- **Ayanamsa Formula**: NKPA = 22° 22' 30" + (Year - 1900) × 50.2388475" + (Year - 1900)² × 0.000111/3600
- **House Cusps**: Placidus system with sidereal correction
- **Sub-Lords**: Proportional division system based on Vimshottari Dasha periods

### Accuracy
- Valid for dates: 5000 BCE to 5000 CE
- Precision: Sub-degree level calculations
- Coordinate System: Sidereal zodiac with KP corrections

---

*Report generated by KP System v1.0 - Swiss Ephemeris Implementation*
"""

        return report

    def _format_planets_table(self, planets_data):
        """Format planets table for markdown"""
        if not planets_data:
            return "No planetary data available."

        table = """| Planet | Cusp | Sign | Sign Lord | Star Lord | Sub Lord |
|--------|------|------|-----------|-----------|----------|
"""
        for planet in planets_data:
            table += f"| {planet['Planet']} | {planet['Cusp']} | {planet['Sign']} | {planet['Sign_Lord']} | {planet['Star_Lord']} | {planet['Sub_Lord']} |\n"

        return table

    def _format_cusps_table(self, cusps_data):
        """Format cusps table for markdown"""
        if not cusps_data:
            return "No cusp data available."

        table = """| Cusp | Degree | Sign | Sign Lord | Star Lord | Sub Lord |
|------|---------|------|-----------|-----------|----------|
"""
        for cusp in cusps_data:
            table += f"| {cusp['Cusp']} | {cusp['Degree']}° | {cusp['Sign']} | {cusp['Sign_Lord']} | {cusp['Star_Lord']} | {cusp['Sub_Lord']} |\n"

        return table

    def _format_ruling_planets(self, ruling_planets):
        """Format ruling planets analysis"""
        if not ruling_planets:
            return "No ruling planets data available."

        analysis = """### Moon (Mo) - Current State
"""
        if 'Mo' in ruling_planets:
            mo = ruling_planets['Mo']
            analysis += f"""- **Sign Lord**: {mo.get('sign_lord', 'N/A')} - Indicates the foundational emotional nature
- **Star Lord**: {mo.get('star_lord', 'N/A')} - Shows the deeper psychological patterns
- **Sub Lord**: {mo.get('sub_lord', 'N/A')} - Reveals specific behavioral tendencies

"""

        analysis += """### Ascendant (Asc) - Life Path
"""
        if 'Asc' in ruling_planets:
            asc = ruling_planets['Asc']
            analysis += f"""- **Sign Lord**: {asc.get('sign_lord', 'N/A')} - Primary life direction and approach
- **Star Lord**: {asc.get('star_lord', 'N/A')} - Karmic life purpose and destiny
- **Sub Lord**: {asc.get('sub_lord', 'N/A')} - Specific life experiences and opportunities

"""

        analysis += """### Day Lord - Birth Day Influence
"""
        if 'Day Lord' in ruling_planets:
            day_lord = ruling_planets['Day Lord']
            analysis += f"""- **Planet**: {day_lord.get('planet', 'N/A')} - Overall planetary influence on the birth day

"""

        return analysis

    def _format_kp_chart(self, kp_chart):
        """Format KP chart layout"""
        if not kp_chart:
            return "No chart data available."

        chart_display = """```
KP Chart Layout (House-wise planetary positions):

    [12]           [1]            [2]
  """ + f"{', '.join(kp_chart.get('12', [])):<10}" + f" | {', '.join(kp_chart.get('1', [])):<10}" + f" | {', '.join(kp_chart.get('2', [])):<10}" + """

[11]                                        [3]
""" + f"{', '.join(kp_chart.get('11', [])):<10}" + "                              " + f"{', '.join(kp_chart.get('3', [])):<10}" + """

[10]                                        [4]
""" + f"{', '.join(kp_chart.get('10', [])):<10}" + "                              " + f"{', '.join(kp_chart.get('4', [])):<10}" + """

    [9]            [8]            [7]
  """ + f"{', '.join(kp_chart.get('9', [])):<10}" + f" | {', '.join(kp_chart.get('8', [])):<10}" + f" | {', '.join(kp_chart.get('7', [])):<10}" + """

       [6]            [5]
     """ + f"{', '.join(kp_chart.get('6', [])):<10}" + f" | {', '.join(kp_chart.get('5', [])):<10}" + """
```

### House-wise Planetary Distribution:
"""

        for house_num in range(1, 13):
            planets = kp_chart.get(str(house_num), [])
            if planets:
                chart_display += f"- **House {house_num}**: {', '.join(planets)}\n"

        return chart_display

    def _format_house_significators(self, house_significators):
        """Format house significators analysis"""
        if not house_significators:
            return "No significator data available."

        analysis = "### Significator Analysis by House\n\n"

        for house_num in range(1, 13):
            if house_num in house_significators:
                significators = house_significators[house_num]
                analysis += f"#### House {house_num}\n"

                if significators.get('strong'):
                    analysis += f"**Strong Significators**: {', '.join(significators['strong'])}\n\n"
                if significators.get('medium'):
                    analysis += f"**Medium Significators**: {', '.join(significators['medium'])}\n\n"
                if significators.get('weak'):
                    analysis += f"**Weak Significators**: {', '.join(significators['weak'])}\n\n"

                analysis += "---\n\n"

        return analysis

    def _format_bhava_chart(self, bhava_chart):
        """Format Bhava Chalit chart comparison"""
        if not bhava_chart:
            return "No Bhava Chalit data available."

        comparison = """### Bhava Chalit vs KP Chart

The Bhava Chalit system uses equal 30° houses from the Ascendant, while KP uses unequal Placidus houses.

**Bhava Chalit House Distribution:**
"""

        for house_num in range(1, 13):
            planets = bhava_chart.get(str(house_num), [])
            if planets:
                comparison += f"- **House {house_num}**: {', '.join(planets)}\n"

        comparison += """
**Key Differences:**
- **KP System**: Uses precise Placidus house cusps with sub-lord analysis
- **Bhava Chalit**: Uses equal houses from Ascendant for timing predictions
- **Combined Usage**: KP for detailed analysis, Bhava Chalit for event timing
"""

        return comparison

# Generate sample report
if __name__ == "__main__":
    generator = KPReportGenerator()
    report = generator.generate_markdown_report(
        year=2024, month=9, day=13, hour=16, minute=18,
        latitude=28.6139, longitude=77.2090, timezone='Asia/Kolkata',
        name="Sample Chart", place="New Delhi, India"
    )
    print(report)